---

- name: Copy binary
  copy:
    src: "{{BINARY}}"
    dest: /usr/bin
    mode: 0755

- name: Get node ID
  command: "cat /etc/gaiad-nodeid"
  changed_when: false
  register: nodeid

- name: gaiad init
  command: "/usr/bin/gaiad init --chain-id={{TESTNET_NAME}} --name=fullnode{{nodeid.stdout_lines[0]}}"
  become: yes
  become_user: gaiad
  args:
    creates: /home/gaiad/.gaiad/config

- name: Copy genesis file
  copy:
    src: "{{GENESISFILE}}"
    dest: /home/gaiad/.gaiad/config/genesis.json
  become: yes
  become_user: gaiad

- name: Copy config.toml file
  copy:
    src: "{{CONFIGFILE}}"
    dest: /home/gaiad/.gaiad/config/config.toml
  become: yes
  become_user: gaiad

